# Generated by Django 3.0.8 on 2020-09-07 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PSS', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PanelStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generation', models.FloatField()),
                ('date_time', models.DateTimeField()),
                ('panel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PSS.Panel')),
            ],
        ),
        migrations.CreateModel(
            name='LoadStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumption', models.FloatField(default=0.0)),
                ('date_time', models.DateTimeField()),
                ('load', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PSS.Load')),
            ],
        ),
    ]
