# Generated by Django 3.0.8 on 2020-09-08 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PSS', '0002_loadstatus_panelstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='panel',
            name='panel_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='panel',
            name='rated_power',
            field=models.FloatField(null=True),
        ),
    ]
