# Generated by Django 3.0.8 on 2020-09-23 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PSS', '0003_auto_20200908_1651'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='usage_stat',
        ),
    ]
