# Generated by Django 3.0.8 on 2020-09-29 07:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('PSS', '0005_auto_20200929_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentstatus',
            name='pay_centre',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='paymentstatus',
            name='amount',
            field=models.FloatField(null=True),
        ),
        migrations.CreateModel(
            name='PowerExchange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('energy_rate_system', models.FloatField(null=True)),
                ('contrib', models.FloatField(null=True)),
                ('consume', models.FloatField(null=True)),
                ('contrib_amount_system', models.FloatField(null=True)),
                ('consume_amount_system', models.FloatField(null=True)),
                ('month', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
