# Generated by Django 3.0.8 on 2020-09-29 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PSS', '0006_auto_20200929_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentstatus',
            name='year',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='powerexchange',
            name='year',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='paymentstatus',
            name='month',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='powerexchange',
            name='month',
            field=models.IntegerField(null=True),
        ),
    ]
