# Generated by Django 3.0.8 on 2020-09-30 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PSS', '0007_auto_20200929_1756'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='consume',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='contrib',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='start_month',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='start_year',
            field=models.IntegerField(null=True),
        ),
    ]
